import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcrypt";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const destinations = [
  // ── Europe ────────────────────────────────────────────────────────────────
  {
    name: "Santorini",
    country: "Grèce",
    shortDescription: "Villages blancs suspendus au-dessus de la mer Égée",
    description: "Santorini est une île volcanique des Cyclades née d'une éruption il y a 3 600 ans. Elle est célèbre pour ses maisons blanches aux coupoles bleues à Oia et Fira, ses plages de sable noir et rouge (Kamari, Perissa) et ses couchers de soleil parmi les plus photographiés au monde.",
    basePrice: 180,
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800",
    gallery: ["https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800", "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800"],
  },
  {
    name: "Côte Amalfitaine",
    country: "Italie",
    shortDescription: "Falaises dorées et villages accrochés à la mer Tyrrhénienne",
    description: "La côte amalfitaine s'étend sur 50 km entre Positano et Vietri sul Mare, dans la région Campanie. Classée au patrimoine mondial de l'UNESCO en 1997, elle est jalonnée de villages aux maisons pastel accrochés à la falaise — Positano, Ravello, Amalfi — et de routes vertigineuses au-dessus de la Méditerranée.",
    basePrice: 160,
    imageUrl: "https://images.unsplash.com/photo-1534445538923-ab38f09f9501?w=800",
    gallery: ["https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800"],
  },
  {
    name: "Islande",
    country: "Islande",
    shortDescription: "Aurores boréales, geysers et paysages lunaires",
    description: "L'Islande est une île volcanique de l'Atlantique Nord avec 130 volcans actifs, dont l'Eyjafjallajökull. La Ring Road (Route 1) de 1 332 km fait le tour de l'île en longeant cascades (Skógafoss, Seljalandsfoss), geysers (Geysir, Strokkur), glaciers (Vatnajökull, le plus grand d'Europe) et sources chaudes. Les aurores boréales sont visibles de septembre à mars.",
    basePrice: 200,
    imageUrl: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800",
    gallery: ["https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800", "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800"],
  },
  {
    name: "Dubrovnik",
    country: "Croatie",
    shortDescription: "La perle de l'Adriatique aux remparts médiévaux",
    description: "Dubrovnik, surnommée la \"perle de l'Adriatique\", est une cité fortifiée du XVe siècle inscrite à l'UNESCO sur la côte dalmate. Ses remparts de 2 km de long dominent la mer Adriatique. Le câble car monte au mont Srđ pour une vue panoramique. Les îles Élaphites et le parc national de Mljet se visitent facilement depuis le port.",
    basePrice: 150,
    imageUrl: "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800",
    gallery: ["https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=800", "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800"],
  },
  {
    name: "Prague",
    country: "République tchèque",
    shortDescription: "La ville aux cent clochers au cœur de la Bohême",
    description: "Prague est la capitale de la République tchèque et l'une des villes médiévales les mieux préservées d'Europe. Le château de Prague (Pražský hrad), le plus grand château médiéval du monde, surplombe la Vltava. Le pont Charles (1357), la place de la Vieille-Ville avec son horloge astronomique et le quartier juif de Josefov composent un centre historique classé à l'UNESCO.",
    basePrice: 110,
    imageUrl: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800",
    gallery: ["https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800", "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800"],
  },
  {
    name: "Barcelone",
    country: "Espagne",
    shortDescription: "Architecture moderniste et plages méditerranéennes",
    description: "Barcelone est la capitale de la Catalogne et la deuxième ville d'Espagne. Antoni Gaudí y a laissé des œuvres majeures : la Sagrada Família (en construction depuis 1882), le parc Güell, la Casa Batlló et la Casa Milà (La Pedrera). Le quartier gothique, les Ramblas et le marché de la Boqueria complètent une ville riche en gastronomie et en vie nocturne.",
    basePrice: 140,
    imageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800",
    gallery: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800", "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800"],
  },
  {
    name: "Amsterdam",
    country: "Pays-Bas",
    shortDescription: "Canaux du XVIIe siècle et musées de renommée mondiale",
    description: "Amsterdam est construite sur 90 îles reliées par 1 281 ponts et traversées par un réseau de canaux du XVIIe siècle (le Grachtengordel, inscrit à l'UNESCO). Le Rijksmuseum abrite les Rembrandt et Vermeer, le musée Van Gogh est le plus visité des Pays-Bas. Le quartier Anne Frank, le Jordaan et la maison des Rembrandt complètent ce patrimoine exceptionnel.",
    basePrice: 135,
    imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
    gallery: ["https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800", "https://images.unsplash.com/photo-1576924542622-772281b13840?w=800"],
  },
  {
    name: "Lisbonne",
    country: "Portugal",
    shortDescription: "Fado, tramways jaunes et azulejos face à l'Atlantique",
    description: "Lisbonne, la plus occidentale des capitales européennes, est bâtie sur sept collines au bord du Tage. Le quartier de l'Alfama avec sa cathédrale et le château São Jorge, le Belém et sa tour du XVIe siècle, le tramway 28 et le Bairro Alto font de Lisbonne une ville attachante. Le fado — musique mélancolique inscrite à l'UNESCO — y est né.",
    basePrice: 120,
    imageUrl: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800",
    gallery: ["https://images.unsplash.com/photo-1513735492246-483525079686?w=800", "https://images.unsplash.com/photo-1548707309-dcebeab9ea9b?w=800"],
  },
  {
    name: "Édimbourg",
    country: "Écosse",
    shortDescription: "Château royal et highlands à portée de la capitale",
    description: "Édimbourg est la capitale de l'Écosse, bâtie sur des roches volcaniques. Le château d'Édimbourg domine la ville depuis le rocher du Castle Rock. Le Royal Mile relie le château au palais de Holyroodhouse (résidence officielle de la famille royale en Écosse). La vieille ville médiévale et la nouvelle ville géorgienne sont ensemble classées à l'UNESCO.",
    basePrice: 130,
    imageUrl: "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800",
    gallery: ["https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800", "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"],
  },
  {
    name: "Vienne",
    country: "Autriche",
    shortDescription: "Capitale impériale des Habsbourg entre opéra et cafés",
    description: "Vienne fut pendant six siècles la capitale du Saint-Empire romain germanique et de l'empire austro-hongrois. Le palais de Schönbrunn (1 441 pièces), le palais du Belvédère et ses Klimt, l'Opéra national, le musée d'histoire de l'art et les cafés viennois centenaires (Café Central, Café Landtmann) composent un patrimoine culturel d'une densité rare.",
    basePrice: 145,
    imageUrl: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800",
    gallery: ["https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800", "https://images.unsplash.com/photo-1573599852326-2d4da0bbe613?w=800"],
  },
  {
    name: "Bruges",
    country: "Belgique",
    shortDescription: "La Venise du Nord et ses chocolats légendaires",
    description: "Bruges est une ville médiévale flamande dont le centre historique est inscrit à l'UNESCO depuis 2000. Ses canaux (qui lui valent le surnom de Venise du Nord), son beffroi du XIIIe siècle, ses béguinages et son lac d'Amour composent un décor de conte. La ville est aussi réputée pour ses chocolatiers artisanaux, ses brasseries et sa dentelle.",
    basePrice: 115,
    imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800",
    gallery: ["https://images.unsplash.com/photo-1520769519539-3bc7ef7e26e2?w=800", "https://images.unsplash.com/photo-1487623562-65c6fc5e6a0d?w=800"],
  },
  {
    name: "Hallstatt",
    country: "Autriche",
    shortDescription: "Le village de conte de fées au bord du lac alpin",
    description: "Hallstatt est un village de 800 habitants dans le Salzkammergut autrichien, classé à l'UNESCO. Construit entre le lac Hallstätter See et la falaise, il est accessible uniquement par bateau ou par une route étroite. La région doit son nom au sel extrait depuis 7 000 ans — la plus ancienne mine de sel du monde s'y trouve. Les glaciers du Dachstein sont à 20 minutes.",
    basePrice: 170,
    imageUrl: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800",
    gallery: ["https://images.unsplash.com/photo-1519491050282-cf00c82424b4?w=800", "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800"],
  },
  {
    name: "Cinque Terre",
    country: "Italie",
    shortDescription: "Cinq villages colorés accrochés aux falaises liguriennes",
    description: "Les Cinque Terre (Monterosso, Vernazza, Corniglia, Manarola, Riomaggiore) sont cinq villages de pêcheurs de la côte ligure reliés par des sentiers de randonnée taillés dans la falaise. Classés à l'UNESCO, ils surplombent la Méditerranée et leurs maisons colorées jaunes, orange et roses dégringolent jusqu'à la mer.",
    basePrice: 155,
    imageUrl: "https://images.unsplash.com/photo-1571536802807-30f4f4d0ebcd?w=800",
    gallery: ["https://images.unsplash.com/photo-1570213490059-a83a2a75a4e4?w=800", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
  },
  {
    name: "Porto",
    country: "Portugal",
    shortDescription: "Vins de Porto et ruelles colorées sur le Douro",
    description: "Porto est la deuxième ville du Portugal, bâtie sur les rives du Douro à 6 km de l'Atlantique. La Ribeira, son quartier historique inscrit à l'UNESCO, est un dédale de ruelles aux maisons coiffées de tuiles. De l'autre côté du fleuve, Vila Nova de Gaia abrite les caves des grandes maisons de porto (Graham's, Sandeman, Taylor's). La librairie Lello (1906) est l'une des plus belles du monde.",
    basePrice: 100,
    imageUrl: "https://images.unsplash.com/photo-1513735492246-483525079686?w=800",
    gallery: ["https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800", "https://images.unsplash.com/photo-1548707309-dcebeab9ea9b?w=800"],
  },
  {
    name: "Séville",
    country: "Espagne",
    shortDescription: "Flamenco, orangers en fleurs et cathédrale gothique",
    description: "Séville est la capitale de l'Andalousie et la quatrième ville d'Espagne. Sa cathédrale gothique est la plus grande du monde (devant Saint-Pierre de Rome). Le palais de l'Alcázar (résidence royale encore en activité) et l'Archivo de Indias forment avec la cathédrale un ensemble inscrit à l'UNESCO. Le quartier de Triana, le flamenco et les tapas sont l'âme de la ville.",
    basePrice: 130,
    imageUrl: "https://images.unsplash.com/photo-1558862107-d49ef2a04d72?w=800",
    gallery: ["https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800", "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800"],
  },
  {
    name: "Dolomites",
    country: "Italie",
    shortDescription: "Pics calcaires vertigineux et alpages du Tyrol du Sud",
    description: "Les Dolomites sont une chaîne de montagne des Alpes orientales dans le nord-est de l'Italie (Trentin-Haut-Adige, Vénétie, Frioul). Classées au patrimoine mondial de l'UNESCO en 2009, leurs tours de calcaire blanc et gris prennent des teintes rose-rouge au coucher du soleil — un phénomène appelé enrosadira. La Tre Cime di Lavaredo est leur emblème.",
    basePrice: 170,
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800",
    gallery: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"],
  },
  {
    name: "Toscane",
    country: "Italie",
    shortDescription: "Cyprès, collines dorées et art de vivre entre Sienne et Florence",
    description: "La Toscane est une région du centre de l'Italie dont Florence fut le berceau de la Renaissance. Sienne et son Palio (course de chevaux biannuelle sur la Piazza del Campo), San Gimignano et ses tours médiévales, les collines du Chianti couvertes de vignes et d'oliviers, et les thermes de Bagno Vignoni composent un tableau intemporel.",
    basePrice: 160,
    imageUrl: "https://images.unsplash.com/photo-1558697698-9300a84a4b0e?w=800",
    gallery: ["https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "https://images.unsplash.com/photo-1549702560-27b78735c6d7?w=800"],
  },
  {
    name: "Bergen",
    country: "Norvège",
    shortDescription: "Porte des fjords norvégiens et quai hanséatique coloré",
    description: "Bergen est la deuxième ville de Norvège et la porte d'entrée des fjords. Le quartier Bryggen — rangée de maisons en bois colorées du XIVe siècle inscrit à l'UNESCO — borde le port. Le funiculaire Fløibanen monte en 8 minutes au mont Fløyen (320 m) pour une vue panoramique. Les excursions sur le Sognefjord (plus long fjord du monde, 204 km) et le Hardangerfjord partent de Bergen.",
    basePrice: 190,
    imageUrl: "https://images.unsplash.com/photo-1469521669194-babb45599def?w=800",
    gallery: ["https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=800", "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800"],
  },
  {
    name: "Tallinn",
    country: "Estonie",
    shortDescription: "Vieille ville médiévale la mieux préservée du nord de l'Europe",
    description: "Tallinn est la capitale de l'Estonie et possède l'une des vieilles villes médiévales les mieux conservées d'Europe du Nord, inscrite à l'UNESCO. Ses remparts du XIIIe siècle, ses tours, la place de l'Hôtel de Ville et le quartier de Toompea (la ville haute) ont traversé les siècles presque intacts. Tallinn est aussi la capitale européenne des startups et de la e-administration.",
    basePrice: 100,
    imageUrl: "https://images.unsplash.com/photo-1548253578-b6dd44dcf18e?w=800",
    gallery: ["https://images.unsplash.com/photo-1541849546-216549ae216d?w=800", "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800"],
  },
  {
    name: "Vallée de la Loire",
    country: "France",
    shortDescription: "Châteaux royaux et vignobles du jardin de la France",
    description: "La Vallée de la Loire est inscrite au patrimoine mondial de l'UNESCO pour son patrimoine architectural et culturel. Les châteaux de Chambord (440 salles, 365 cheminées), Chenonceau (construit sur le Cher), Amboise, Villandry et Azay-le-Rideau jalonnent le fleuve royal. La région produit Sancerre, Pouilly-Fumé, Vouvray et Muscadet.",
    basePrice: 125,
    imageUrl: "https://images.unsplash.com/photo-1549702560-27b78735c6d7?w=800",
    gallery: ["https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800", "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800"],
  },
  {
    name: "Algarve",
    country: "Portugal",
    shortDescription: "Falaises d'or et plages secrètes de la côte atlantique",
    description: "L'Algarve est la région la plus méridionale du Portugal, bordée par l'Atlantique sur 155 km. Ses falaises de grès ocre sculptées en arches, grottes et pitons (Ponta da Piedade, Praia da Marinha) sont uniques en Europe. Lagos, Sagres et le cap Saint-Vincent — le point le plus sud-ouest du continent européen — complètent ce littoral exceptionnel.",
    basePrice: 115,
    imageUrl: "https://images.unsplash.com/photo-1555842605-0b5d31951874?w=800",
    gallery: ["https://images.unsplash.com/photo-1513735492246-483525079686?w=800", "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800"],
  },
  {
    name: "Côte d'Azur",
    country: "France",
    shortDescription: "Nice, Monaco et Saint-Tropez sous le soleil méditerranéen",
    description: "La Côte d'Azur s'étend sur 300 km de Cassis à Menton, le long de la Méditerranée. Nice et sa promenade des Anglais, la principauté de Monaco avec son casino et son Grand Prix de F1, Antibes et le musée Picasso, Cannes et son festival, Saint-Tropez et ses plages de Pampelonne définissent la Riviera française.",
    basePrice: 200,
    imageUrl: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800",
    gallery: ["https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "https://images.unsplash.com/photo-1570213490059-a83a2a75a4e4?w=800"],
  },
  {
    name: "Îles Féroé",
    country: "Danemark",
    shortDescription: "Falaises vertigineuses et villages isolés dans l'Atlantique Nord",
    description: "L'archipel des Îles Féroé est un territoire autonome du Danemark composé de 18 îles volcaniques dans l'Atlantique Nord, entre Norvège et Islande. Ses falaises de basalte à pic sur la mer, ses maisons aux toits de tourbe verte, ses lacs suspendus au-dessus de l'océan (Sørvágsvatn) et ses troupeaux de moutons (plus que d'habitants) forment un paysage surréaliste.",
    basePrice: 195,
    imageUrl: "https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=800",
    gallery: ["https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800", "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800"],
  },
  {
    name: "Açores",
    country: "Portugal",
    shortDescription: "Volcans actifs et lacs émeraude dans l'Atlantique",
    description: "Les Açores sont un archipel de 9 îles volcaniques du Portugal situées à 1 500 km à l'ouest de Lisbonne. São Miguel, la plus grande, abrite le lac Sete Cidades (double lac dans un cratère volcanique), les caldeiras bouillonnantes de Furnas et les sources hydrothermales de Terra Nostra. L'observation des baleines et dauphins (30 espèces recensées) est une activité phare.",
    basePrice: 130,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    gallery: ["https://images.unsplash.com/photo-1469521669194-babb45599def?w=800", "https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=800"],
  },
  {
    name: "Kotor",
    country: "Monténégro",
    shortDescription: "Vieille ville vénitienne dans les bras d'un fjord adriatique",
    description: "Kotor est une cité médiévale inscrite à l'UNESCO nichée au fond de la baie de Kotor, l'unique fjord de la Méditerranée. Ses remparts du XIVe siècle grimpent sur 4,5 km jusqu'à la forteresse de San Giovanni (280 m). L'architecture vénitienne témoigne de 400 ans de domination de la Sérénissime. La ville est aussi surnommée la \"ville des chats\".",
    basePrice: 105,
    imageUrl: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=800",
    gallery: ["https://images.unsplash.com/photo-1555990793-da11153b2473?w=800", "https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=800"],
  },

  // ── Asie ──────────────────────────────────────────────────────────────────
  {
    name: "Kyoto",
    country: "Japon",
    shortDescription: "L'ancienne capitale impériale aux mille temples",
    description: "Kyoto fut la capitale du Japon pendant plus de mille ans (794-1868) et concentre 17 sites classés à l'UNESCO. Ses 1 600 temples bouddhistes (Kinkaku-ji le Pavillon d'or, Ryoan-ji et son jardin zen), ses 400 sanctuaires shinto dont le Fushimi Inari aux 10 000 torii rouges, le quartier de Gion (geishas) et la forêt de bambous d'Arashiyama en font la capitale culturelle du Japon.",
    basePrice: 220,
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
    gallery: ["https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800", "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800"],
  },
  {
    name: "Bali",
    country: "Indonésie",
    shortDescription: "L'île des dieux entre rizières en terrasses et temples sacrés",
    description: "Bali est la seule île majoritairement hindoue d'Indonésie (83 % de sa population). Le subak, son système d'irrigation des rizières en terrasses vieux de 1 000 ans, est inscrit à l'UNESCO. Ubud est son centre culturel (musées, danses kecak, artisans), Seminyak et Kuta ses plages de surf, Tanah Lot et Uluwatu ses temples perchés sur des falaises face à l'océan Indien.",
    basePrice: 130,
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    gallery: ["https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800", "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800"],
  },
  {
    name: "Tokyo",
    country: "Japon",
    shortDescription: "Mégapole futuriste entre tradition et ultramodernité",
    description: "Tokyo est la plus grande agglomération urbaine du monde avec 37 millions d'habitants. Capitale du Japon depuis 1869, elle juxtapose quartiers ultramodernes (Shinjuku, Shibuya et son célèbre carrefour piéton) et temples millénaires (Senso-ji à Asakusa), restaurants étoilés (ville avec le plus d'étoiles Michelin au monde), marchés aux poissons de Tsukiji et jardins impériaux.",
    basePrice: 240,
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    gallery: ["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800", "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800"],
  },
  {
    name: "Hanoï",
    country: "Vietnam",
    shortDescription: "Capitale millénaire et vieux quartier des 36 corporations",
    description: "Hanoï est la capitale du Vietnam depuis plus de 1 000 ans. Son vieux quartier (Phố Cổ), structuré selon les 36 corporations médiévales, est un dédale de ruelles commerçantes. Le lac Hoan Kiem et la pagode Ngoc Son, le mausolée d'Hô Chi Minh, le musée ethnologique et la gastronomie de rue (phở, bún chả, bánh mì) font de Hanoï une ville à découvrir lentement.",
    basePrice: 75,
    imageUrl: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800",
    gallery: ["https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800", "https://images.unsplash.com/photo-1528127269322-539801943592?w=800"],
  },
  {
    name: "Hoi An",
    country: "Vietnam",
    shortDescription: "Cité ancienne et lanternes colorées au bord du Thu Bồn",
    description: "Hoi An est un port marchand du XVe siècle inscrit à l'UNESCO, au centre du Vietnam. Sa vieille ville (Phố Cổ) rassemble des maisons-tubes chinoises, des temples japonais et des bâtiments coloniaux français. Chaque soir, les lanternes de soie illuminent les ruelles. Ses tailleurs (plus de 400 boutiques) confectionnent des vêtements sur mesure en 24 heures.",
    basePrice: 80,
    imageUrl: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800",
    gallery: ["https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800", "https://images.unsplash.com/photo-1528127269322-539801943592?w=800"],
  },
  {
    name: "Chiang Mai",
    country: "Thaïlande",
    shortDescription: "Ancienne capitale du royaume Lanna et ses 300 temples",
    description: "Chiang Mai est la capitale du nord de la Thaïlande, fondée en 1296 comme capitale du royaume Lanna. Elle compte plus de 300 temples dont le Wat Phra That Doi Suthep sur la montagne qui domine la ville. Les marchés nocturnes de la vieille ville, les sanctuaires d'éléphants éthiques, les cours de cuisine thaïe et les treks en montagne (Karen, Hmong) en font une base incontournable.",
    basePrice: 90,
    imageUrl: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800",
    gallery: ["https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800", "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800"],
  },
  {
    name: "Luang Prabang",
    country: "Laos",
    shortDescription: "Ville royale bouddhiste au confluent du Mékong et du Nam Khan",
    description: "Luang Prabang est l'ancienne capitale royale du Laos, inscrite à l'UNESCO en 1995. Chaque matin à l'aube, des centaines de moines en robe safran défilent dans les rues pour la cérémonie de l'aumône (tak bat). Ses 33 temples dorés, dont le Wat Xieng Thong, ses bungalows au bord du Mékong et les cascades de Kuang Si (piscines turquoise en terrasses) en font une destination spirituelle unique.",
    basePrice: 85,
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
    gallery: ["https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800", "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800"],
  },
  {
    name: "Singapour",
    country: "Singapour",
    shortDescription: "Cité-État futuriste entre jardins dans les nuages et gastronomie",
    description: "Singapour est une cité-État de 5,9 millions d'habitants sur une île de 728 km². Indépendante depuis 1965, elle est l'un des centres financiers et commerciaux majeurs du monde. Les Gardens by the Bay et leurs Supertrees, le Marina Bay Sands, Chinatown, Little India, les hawker centres (marchés de rue classés à l'UNESCO en 2020) et le jardin botanique font la richesse de cette ville multiculturelle.",
    basePrice: 210,
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
    gallery: ["https://images.unsplash.com/photo-1508964942454-1a56651d54ac?w=800", "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800"],
  },
  {
    name: "Séoul",
    country: "Corée du Sud",
    shortDescription: "Palais Joseon, K-pop et gastronomie dans la capitale coréenne",
    description: "Séoul est la capitale de la Corée du Sud avec 10 millions d'habitants (25 millions avec l'agglomération). Les cinq palais de la dynastie Joseon (Gyeongbokgung, Changdeokgung), le quartier branché de Hongdae, Insadong et ses galeries, la gastronomie (bibimbap, bulgogi, kimchi) et la culture pop coréenne (K-pop, K-drama) rayonnant sur le monde entier font de Séoul une destination incontournable.",
    basePrice: 175,
    imageUrl: "https://images.unsplash.com/photo-1538485399081-7c8272404f55?w=800",
    gallery: ["https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800", "https://images.unsplash.com/photo-1575747819096-7e3b6ee9e1b3?w=800"],
  },
  {
    name: "Tbilissi",
    country: "Géorgie",
    shortDescription: "Capitale caucasienne aux balcons sculptés et bains souffrés",
    description: "Tbilissi est la capitale de la Géorgie, pays du Caucase fondée au Ve siècle. La vieille ville (Abanotubani) est traversée par la rivière Kura et connue pour ses bains souffrés (dômes en brique). Les maisons aux balcons en bois ouvragés, la forteresse de Narikala, la cathédrale Sainte-Trinité et les vins géorgiens (la plus ancienne tradition viticole du monde, 8 000 ans) définissent cette ville attachante.",
    basePrice: 80,
    imageUrl: "https://images.unsplash.com/photo-1567573642-7b50b14c9c9e?w=800",
    gallery: ["https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800", "https://images.unsplash.com/photo-1569230919100-d3fd5e1132f4?w=800"],
  },
  {
    name: "Baie d'Halong",
    country: "Vietnam",
    shortDescription: "3 000 îlots karstiques émergent de la mer d'Émeraude",
    description: "La Baie d'Halong (\"là où le dragon descend dans la mer\") est un site naturel inscrit deux fois à l'UNESCO (1994 et 2000) dans la province de Quảng Ninh. Ses 1 969 îlots et îles de calcaire couverts de végétation tropicale s'élèvent de la mer turquoise. Elle se visite à bord de jonques traditionnelles avec excursions en kayak dans les grottes (Grotte des Merveilles) et les villages de pêcheurs flottants.",
    basePrice: 95,
    imageUrl: "https://images.unsplash.com/photo-1557640935-87e1e98c5dbf?w=800",
    gallery: ["https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800", "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800"],
  },
  {
    name: "Cappadoce",
    country: "Turquie",
    shortDescription: "Cheminées de fées, villes souterraines et montgolfières",
    description: "La Cappadoce est une région d'Anatolie centrale (Turquie) dont le paysage est le résultat de l'érosion de coulées volcaniques sur des millions d'années. Le parc national de Göreme (UNESCO) est parsemé de \"cheminées de fées\", de vallées sculptées (Rose Valley, Love Valley) et d'églises rupestres byzantines. Les villes souterraines de Derinkuyu et Kaymaklı pouvaient abriter 20 000 personnes. Les vols en montgolfière au lever du soleil sont le symbole de la région.",
    basePrice: 135,
    imageUrl: "https://images.unsplash.com/photo-1565073624497-7144969fe4c3?w=800",
    gallery: ["https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800", "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800"],
  },
  {
    name: "Jaisalmer",
    country: "Inde",
    shortDescription: "La cité dorée du Rajasthan aux portes du désert du Thar",
    description: "Jaisalmer est une ville du Rajasthan occidental construite entièrement en grès jaune, ce qui lui vaut le surnom de \"cité d'or\". Son fort médiéval Sonar Quila (XIIe siècle), encore habité par 3 000 personnes, abrite temples jaïns et palais. Les havélis (demeures de marchands) aux façades ciselées de Patwon Ki Haveli et les safaris en dromadaire dans les dunes de Khuri complètent cette destination unique.",
    basePrice: 85,
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800",
    gallery: ["https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800", "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800"],
  },

  // ── Afrique & Moyen-Orient ────────────────────────────────────────────────
  {
    name: "Marrakech",
    country: "Maroc",
    shortDescription: "La ville ocre aux souks envoûtants et aux riads fleuris",
    description: "Marrakech est la quatrième ville du Maroc et l'une des quatre villes impériales. Sa médina (UNESCO) est un labyrinthe de souks structurés par corps de métiers (tanneurs, dinandiers, tisserands). La place Jemaa el-Fna est classée par l'UNESCO comme patrimoine culturel immatériel. Les jardins de la Majorelle (propriété d'Yves Saint Laurent), le palais Bahia et les tombeaux Saadiens complètent la visite.",
    basePrice: 90,
    imageUrl: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800",
    gallery: ["https://images.unsplash.com/photo-1548018560-c7196aca8d48?w=800", "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800"],
  },
  {
    name: "Petra",
    country: "Jordanie",
    shortDescription: "La cité nabatéenne rose sculptée dans le grès",
    description: "Petra est l'ancienne capitale du royaume nabatéen, taillée dans le grès rose de la vallée d'Arabah. Fondée au VIe siècle av. J.-C., elle est inscrite à l'UNESCO et figure parmi les nouvelles Sept Merveilles du Monde. Le Siq (gorge de 1,2 km) débouche sur le Trésor (Al-Khazneh, 40 m de haut), le monument le plus photographié. Le site compte plus de 800 tombeaux, temples et monastères dont le Deir (8 m de haut).",
    basePrice: 110,
    imageUrl: "https://images.unsplash.com/photo-1580834341580-8c17a3a630ca?w=800",
    gallery: ["https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800", "https://images.unsplash.com/photo-1548011241-46c4fab2d5c2?w=800"],
  },
  {
    name: "Le Cap",
    country: "Afrique du Sud",
    shortDescription: "Table Mountain, vignobles et bout du continent africain",
    description: "Le Cap (Cape Town) est la capitale législative de l'Afrique du Sud, fondée par la Compagnie néerlandaise des Indes orientales en 1652. La montagne de la Table (1 086 m), classée nouvelle Merveille naturelle du Monde, est accessible par télécabine. Le cap de Bonne-Espérance et la colonie de pingouins africains de Boulder's Beach, les vignobles de Stellenbosch et la prison de Robben Island (où fut emprisonné Mandela) font du Cap une destination d'exception.",
    basePrice: 165,
    imageUrl: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800",
    gallery: ["https://images.unsplash.com/photo-1565400584088-9f92b3f65dd5?w=800", "https://images.unsplash.com/photo-1578338076619-2cf25a6f06ff?w=800"],
  },
  {
    name: "Zanzibar",
    country: "Tanzanie",
    shortDescription: "Archipel de l'océan Indien entre Stone Town et plages de corail",
    description: "Zanzibar est un archipel tanzanien de l'océan Indien composé de l'île Unguja (Zanzibar) et de Pemba. Stone Town, la vieille ville de Zanzibar, est inscrite à l'UNESCO pour son architecture swahilie-arabo-indienne (portes en teck sculptées, palais du sultan). L'île fut le centre du commerce des épices (clous de girofle, cannelle, poivre) et de l'esclavage en Afrique de l'Est.",
    basePrice: 155,
    imageUrl: "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800",
    gallery: ["https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800", "https://images.unsplash.com/photo-1565400584088-9f92b3f65dd5?w=800"],
  },
  {
    name: "Essaouira",
    country: "Maroc",
    shortDescription: "Cité des vents, remparts portugais et médina bleue",
    description: "Essaouira est une ville côtière de l'Atlantique marocain (région Marrakech-Safi), ancienne cité commerciale portugaise du XVIe siècle. Sa médina inscrite à l'UNESCO est construite selon un plan en damier par l'architecte français Théodore Cornut (1765). Ses remparts en esplanade sur l'océan, ses ateliers d'artisans (marqueterie de thuya), ses galeries d'art et son festival gnaoua international en font une ville ouverte et créative.",
    basePrice: 75,
    imageUrl: "https://images.unsplash.com/photo-1548018560-c7196aca8d48?w=800",
    gallery: ["https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800", "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800"],
  },
  {
    name: "Serengeti",
    country: "Tanzanie",
    shortDescription: "La grande migration et les Big Five sur 30 000 km²",
    description: "Le parc national du Serengeti (Tanzanie) est le plus ancien et le plus célèbre d'Afrique, inscrit à l'UNESCO. Il couvre 30 000 km² de plaines d'herbe rase et de savane arborée. Chaque année, 1,5 million de gnous, 250 000 zèbres et 500 000 gazelles migrent en cercle entre le Serengeti et le Masaï Mara kényan — le plus grand mouvement terrestre d'animaux sur Terre.",
    basePrice: 320,
    imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800",
    gallery: ["https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800", "https://images.unsplash.com/photo-1578338076619-2cf25a6f06ff?w=800"],
  },
  {
    name: "Namibie",
    country: "Namibie",
    shortDescription: "Désert du Namib, dunes de Sossusvlei et côte des Squelettes",
    description: "La Namibie est un pays d'Afrique australe indépendant depuis 1990. Le désert du Namib est le plus ancien du monde (80 millions d'années). Sossusvlei et ses dunes rouges de 325 m de haut, le parc Etosha (22 000 km², éléphants, lions, rhinocéros noirs), la Côte des Squelettes avec ses épaves et ses otaries, et Lüderitz, ville fantôme de la ruée vers le diamant, composent un pays unique.",
    basePrice: 200,
    imageUrl: "https://images.unsplash.com/photo-1562077981-4d7eafd44932?w=800",
    gallery: ["https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800", "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800"],
  },
  {
    name: "Dubaï",
    country: "Émirats arabes unis",
    shortDescription: "Mégapole du futur entre gratte-ciel records et désert",
    description: "Dubaï est l'un des sept émirats des Émirats arabes unis, transformé en 50 ans d'un village de pêcheurs en métropole mondiale. Le Burj Khalifa (828 m, la plus haute tour du monde), le Palm Jumeirah (île artificielle en forme de palmier), le Burj Al Arab et les souks d'or et d'épices de Deira illustrent ce contraste saisissant entre tradition et modernité.",
    basePrice: 300,
    imageUrl: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800",
    gallery: ["https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800", "https://images.unsplash.com/photo-1565127771579-d0b2e6e1cde2?w=800"],
  },

  // ── Amériques ─────────────────────────────────────────────────────────────
  {
    name: "Patagonie",
    country: "Argentine",
    shortDescription: "Le bout du monde entre glaciers de Los Glaciares et mont Fitz Roy",
    description: "La Patagonie argentine s'étend sur 780 000 km² au sud de l'Argentine. Le parc national Los Glaciares (UNESCO) abrite le glacier Perito Moreno — l'un des rares qui avance encore — et les pics granitiques du Fitz Roy (3 405 m) et du Cerro Torre. La péninsule Valdés accueille baleines australes, éléphants de mer et manchots de Magellan.",
    basePrice: 260,
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    gallery: ["https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"],
  },
  {
    name: "Machu Picchu",
    country: "Pérou",
    shortDescription: "La citadelle inca suspendue dans les Andes à 2 430 m",
    description: "Machu Picchu est une cité inca construite vers 1450 à 2 430 m d'altitude dans les Andes péruviennes. Abandonnée lors de la conquête espagnole et \"redécouverte\" en 1911 par Hiram Bingham, elle est inscrite à l'UNESCO et figure parmi les nouvelles Sept Merveilles du Monde. Le site comprend 200 constructions dont le Temple du Soleil (Intihuatana) et la Plaza Principal. L'Inca Trail (45 km, 4 jours) est le trek le plus célèbre d'Amérique du Sud.",
    basePrice: 190,
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800",
    gallery: ["https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800", "https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800"],
  },
  {
    name: "Rio de Janeiro",
    country: "Brésil",
    shortDescription: "Carnaval, samba, Pain de Sucre et plages mythiques",
    description: "Rio de Janeiro est la deuxième ville du Brésil, ancienne capitale (1763-1960). Le Christ Rédempteur sur le Corcovado (38 m, inauguré en 1931) est l'une des nouvelles Sept Merveilles du Monde. Le Pain de Sucre (396 m), les plages d'Ipanema et Copacabana, le carnaval (le plus grand du monde, 2 millions de personnes par jour) et les favelas aux art muraux extraordinaires en font une ville inoubliable.",
    basePrice: 175,
    imageUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800",
    gallery: ["https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=800", "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800"],
  },
  {
    name: "New York",
    country: "États-Unis",
    shortDescription: "La ville qui ne dort jamais entre skyline et Central Park",
    description: "New York est la plus grande ville des États-Unis avec 8,3 millions d'habitants (20 millions dans la métropole). Ses cinq boroughs (Manhattan, Brooklyn, Queens, le Bronx, Staten Island) abritent la Statue de la Liberté (cadeau de la France en 1886), Central Park (341 ha), le Met, le MoMA, le Carnegie Hall, Wall Street, Times Square et plus de 24 000 restaurants.",
    basePrice: 280,
    imageUrl: "https://images.unsplash.com/photo-1490644658840-3f2e3f8c5625?w=800",
    gallery: ["https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800", "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800"],
  },
  {
    name: "La Havane",
    country: "Cuba",
    shortDescription: "Voitures américaines des années 50 et architecture coloniale",
    description: "La Havane est la capitale et la plus grande ville de Cuba. Son centre historique (Habana Vieja) est inscrit à l'UNESCO depuis 1982 pour son architecture coloniale espagnole des XVIe-XVIIIe siècles. La ville est aussi connue pour ses voitures américaines des années 40-50 (environ 60 000 en état de marche), sa musique (son, salsa, rumba), ses bars mythiques (La Bodeguita del Medio, El Floridita, fréquentés par Hemingway) et ses cigares.",
    basePrice: 120,
    imageUrl: "https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=800",
    gallery: ["https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800", "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800"],
  },
  {
    name: "Cartagena",
    country: "Colombie",
    shortDescription: "Cité coloniale fortifiée sur la mer des Caraïbes",
    description: "Cartagena de Indias est un port colombien fondé en 1533, inscrit à l'UNESCO. Son centro histórico est entouré de 11 km de remparts construits pour protéger les galions espagnols transportant l'or et l'argent des Amériques vers l'Espagne. Ses rues aux balcons couverts de bougainvillées, ses palais de couleurs vives, ses plazas animées et les îles coralliennes du parc national Corales del Rosario en font une destination emblématique.",
    basePrice: 110,
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
    gallery: ["https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=800", "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800"],
  },
  {
    name: "Banff",
    country: "Canada",
    shortDescription: "Lacs turquoise et montagnes Rocheuses dans le premier parc national canadien",
    description: "Banff est la ville du premier parc national du Canada (1885), dans les Rocheuses albertaines. Le lac Louise et son eau vert émeraude, le lac Moraine entouré des Dix Sommets, la promenade des Glaciers (Icefields Parkway, 230 km) et les sources chaudes de Banff attirent 4 millions de visiteurs par an. L'ours grizzly, l'élan et le wapiti vivent à proximité de la ville.",
    basePrice: 230,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    gallery: ["https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800", "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800"],
  },
  {
    name: "Cusco",
    country: "Pérou",
    shortDescription: "Nombril du monde inca à 3 400 m d'altitude dans les Andes",
    description: "Cusco est l'ancienne capitale de l'empire inca (Tawantinsuyu), à 3 400 m d'altitude dans les Andes péruviennes. En quechua, son nom signifie \"nombril du monde\". Les fondations incas en pierres parfaitement assemblées sans mortier supportent les bâtiments coloniaux espagnols. La Qorikancha (temple du Soleil), la Plaza de Armas, la citadelle de Sacsayhuamán et la vallée sacrée de l'Urubamba se visitent depuis ici.",
    basePrice: 130,
    imageUrl: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800",
    gallery: ["https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800", "https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800"],
  },
  {
    name: "Salar d'Uyuni",
    country: "Bolivie",
    shortDescription: "Le plus grand désert de sel du monde à 3 650 m d'altitude",
    description: "Le Salar d'Uyuni est le plus grand désert de sel du monde avec 10 582 km², situé dans le département de Potosí en Bolivie à 3 650 m d'altitude. En saison des pluies (décembre-mars), une fine couche d'eau transforme le salar en miroir parfait reflétant le ciel. Il contient 50 à 70 % des réserves mondiales de lithium. L'île Incahuasi, couverte de cactus géants au centre du salar, est une escale iconique.",
    basePrice: 110,
    imageUrl: "https://images.unsplash.com/photo-1547516952-2097b1c23a7f?w=800",
    gallery: ["https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800", "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800"],
  },
  {
    name: "Valparaíso",
    country: "Chili",
    shortDescription: "42 collines colorées et street art face au Pacifique",
    description: "Valparaíso est un port chilien inscrit à l'UNESCO, bâti sur 42 cerros (collines) dominant l'océan Pacifique. 15 funiculaires (ascensores) historiques relient la ville basse au port. Ses ruelles escarpées aux maisons de tôle ondulée multicolores sont couvertes de fresques murales parmi les plus impressionnantes d'Amérique du Sud. La ville fut le principal port de la côte Pacifique avant l'ouverture du canal de Panama.",
    basePrice: 105,
    imageUrl: "https://images.unsplash.com/photo-1559732277-7453b141e3a1?w=800",
    gallery: ["https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800", "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"],
  },
  {
    name: "Galápagos",
    country: "Équateur",
    shortDescription: "Archipel volcanique qui a inspiré la théorie de Darwin",
    description: "Les îles Galápagos sont un archipel équatorien de 18 îles principales situé à 1 000 km de la côte continentale. C'est en observant les pinsons des Galápagos en 1835 que Charles Darwin développa sa théorie de l'évolution. L'archipel, inscrit à l'UNESCO depuis 1978, abrite des espèces endémiques uniques : tortues géantes (jusqu'à 300 kg), iguanes marins, lions de mer, fous à pieds bleus, manchots des Galápagos.",
    basePrice: 380,
    imageUrl: "https://images.unsplash.com/photo-1560275619-4cc5fa59d3ae?w=800",
    gallery: ["https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800", "https://images.unsplash.com/photo-1578338076619-2cf25a6f06ff?w=800"],
  },

  // ── Océanie & Pacifique ───────────────────────────────────────────────────
  {
    name: "Sydney",
    country: "Australie",
    shortDescription: "Opéra sur l'eau, Harbour Bridge et plage de Bondi",
    description: "Sydney est la plus grande ville d'Australie avec 5,3 millions d'habitants, fondée en 1788 comme colonie pénitentiaire britannique. L'Opéra de Sydney (UNESCO, inauguré en 1973, conçu par Jørn Utzon) et le Harbour Bridge (134 m de haut, 1932) dominent l'un des plus beaux ports naturels du monde. Bondi Beach, les Blue Mountains à 90 minutes et la Barossa Valley complètent l'offre.",
    basePrice: 250,
    imageUrl: "https://images.unsplash.com/photo-1523428096881-5bd79d043006?w=800",
    gallery: ["https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800", "https://images.unsplash.com/photo-1519491050282-cf00c82424b4?w=800"],
  },
  {
    name: "Bora Bora",
    country: "Polynésie française",
    shortDescription: "Lagon turquoise et bungalows sur pilotis en Polynésie",
    description: "Bora Bora est une île volcanique de Polynésie française entourée d'un lagon et d'un récif corallien. Le mont Otemanu (727 m), ancien volcan couvert de végétation tropicale, domine l'île depuis le lagon. L'île est mondialement connue pour ses bungalows sur pilotis au-dessus de l'eau turquoise, ses raies manta et ses requins à pointe noire que l'on côtoie en snorkeling.",
    basePrice: 450,
    imageUrl: "https://images.unsplash.com/photo-1589979481223-deb893043163?w=800",
    gallery: ["https://images.unsplash.com/photo-1562372323-2e6f95f4e834?w=800", "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800"],
  },
  {
    name: "Queenstown",
    country: "Nouvelle-Zélande",
    shortDescription: "Capitale mondiale de l'aventure dans les Alpes du Sud",
    description: "Queenstown est une ville de 15 000 habitants sur les rives du lac Wakatipu dans les Alpes du Sud néo-zélandaises. Elle est la capitale mondiale des sports extrêmes : le premier saut en bungee commercial du monde y a été organisé en 1988 (Kawarau Bridge, 43 m). Ski à Remarkables et Coronet Peak, saut en parachute, rafting sur le Shotover, fjords de Milford Sound à 3 heures.",
    basePrice: 240,
    imageUrl: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800",
    gallery: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800", "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800"],
  },
  {
    name: "Palawan",
    country: "Philippines",
    shortDescription: "Lagons secrets et rivière souterraine dans la mer de Sulu",
    description: "Palawan est une province insulaire des Philippines régulièrement élue meilleure île du monde par les magazines de voyage. El Nido et ses lagons cachés entre falaises karstiques, Coron et ses lacs de mer (Barracuda Lake, Kayangan Lake) et épaves de la Seconde Guerre mondiale, Puerto Princesa et sa rivière souterraine navigable de 8,2 km (UNESCO) composent un archipel encore préservé.",
    basePrice: 120,
    imageUrl: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800",
    gallery: ["https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800", "https://images.unsplash.com/photo-1589979481223-deb893043163?w=800"],
  },
  {
    name: "Maldives",
    country: "Maldives",
    shortDescription: "1 192 îles coralliennes dans l'océan Indien",
    description: "Les Maldives sont un État insulaire de l'océan Indien composé de 26 atolls et 1 192 îles coralliennes, dont 200 sont habitées. C'est le pays le plus plat du monde (altitude maximale 2,4 m) et l'un des plus menacés par la montée des eaux. Ses lagons de cristal, ses récifs coralliens (700 espèces de poissons), ses raies manta et ses baleines-requins, et ses resorts sur pilotis en font la destination romantique ultime.",
    basePrice: 500,
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
    gallery: ["https://images.unsplash.com/photo-1589979481223-deb893043163?w=800", "https://images.unsplash.com/photo-1562372323-2e6f95f4e834?w=800"],
  },
  {
    name: "Sri Lanka",
    country: "Sri Lanka",
    shortDescription: "Rocher-forteresse de Sigiriya, temple de la Dent et thé de Ceylan",
    description: "Le Sri Lanka (anciennement Ceylan) est une île de l'océan Indien au sud de l'Inde. Sigiriya, le rocher-lion de 200 m de haut (Ve siècle, forteresse royale inscrite à l'UNESCO), Kandy et le temple de la Dent de Bouddha (relique sacrée), le train de montagne Kandy-Ella traversant les plantations de thé, et les plages de Mirissa fréquentées par les baleines bleues composent une île aux mille facettes.",
    basePrice: 95,
    imageUrl: "https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=800",
    gallery: ["https://images.unsplash.com/photo-1528181304800-259b08848526?w=800", "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800"],
  },
];

async function main() {
  console.log("Nettoyage de la base...");
  await prisma.reservation.deleteMany();
  await prisma.destination.deleteMany();
  await prisma.user.deleteMany();

  console.log(`Création de ${destinations.length} destinations...`);
  for (const dest of destinations) {
    await prisma.destination.create({ data: dest });
  }

  console.log("Création des utilisateurs...");
  const hashedPassword = await bcrypt.hash("password123", 12);

  await prisma.user.create({
    data: {
      name: "Admin Reservia",
      email: "admin@reservia.fr",
      password: await bcrypt.hash("admin1234", 12),
      role: "ADMIN",
    },
  });

  await prisma.user.create({
    data: {
      name: "Marie Dupont",
      email: "marie@example.fr",
      password: hashedPassword,
      role: "USER",
    },
  });

  console.log(`✅ Seed terminé — ${destinations.length} destinations, 1 admin, 1 utilisateur.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
